/**
 * Canonical project schema and version field handling.
 *
 * Currently only version 1 exists. The schema constants defined here
 * are used by validators.ts and migrations.ts to enforce structure.
 */

/** Current project schema version. */
export const PROJECT_VERSION = 1 as const;

/** All known schema versions (for migration support). */
export const KNOWN_VERSIONS: readonly number[] = [1];

/** Maximum number of pages in a project. */
export const MAX_PAGES = 4;

/** Maximum number of cards per page. */
export const MAX_CARDS_PER_PAGE = 20;

/** Maximum upload file size in bytes (5 MB). */
export const MAX_UPLOAD_BYTES = 5 * 1024 * 1024;

/** Maximum image dimension after client-side resize. */
export const MAX_IMAGE_DIMENSION = 1200;

/** Slug length generated by Math.random().toString(36).slice(2,10). */
export const SLUG_LENGTH = 8;

/** Regex for valid slug characters. */
export const SLUG_PATTERN = /^[a-zA-Z0-9_-]+$/;
